// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bufio

import (
	stdbufio "bufio"
	"io"
	"reflect"
	"unsafe"

	"github.com/pgavlin/text"
)

// SplitFunc is the signature of the split function used to tokenize the
// input. The arguments are an initial substring of the remaining unprocessed
// data and a flag, atEOF, that reports whether the Reader has no more data
// to give. The return values are the number of bytes to advance the input
// and the next token to return to the user, if any, plus an error, if any.
//
// Scanning stops if the function returns an error, in which case some or all
// of the input may be discarded. If that error is ErrFinalToken, scanning
// stops with no error. A non-nil token delivered with ErrFinalToken will be
// the last token.
//
// Otherwise, the Scanner advances the input. If the token is not nil,
// the Scanner returns it to the user. If the token is nil, the Scanner reads
// more data and continues scanning; if there is no more data--if atEOF was
// true--the Scanner returns. If the data does not yet hold a complete token,
// for instance if it has no newline while scanning lines, a SplitFunc can
// return (0, nil, nil) to signal the Scanner to read more data into the slice
// and try again with a longer slice starting at the same point in the input.
//
// The function is never called with an empty data slice unless atEOF is true.
// If atEOF is true, however, data may be non-empty and, as always, holds
// unprocessed text.
type SplitFunc = stdbufio.SplitFunc

// Errors returned by Scanner.
var (
	ErrTooLong         = stdbufio.ErrTooLong
	ErrNegativeAdvance = stdbufio.ErrNegativeAdvance
	ErrAdvanceTooFar   = stdbufio.ErrAdvanceTooFar
	ErrBadReadCount    = stdbufio.ErrBadReadCount
)

// ErrFinalToken is a special sentinel error value. It is intended to be
// returned by a SplitFunc to indicate that the token being delivered with
// the error is the last token and scanning should stop after this one.
var ErrFinalToken = stdbufio.ErrFinalToken

// MaxScanTokenSize is the maximum size used to buffer a token unless the
// user provides an explicit buffer with Scanner.Buffer. The actual maximum
// token size may be smaller as the buffer may need to include, for instance,
// a newline.
const MaxScanTokenSize = stdbufio.MaxScanTokenSize

// Scanner[S] provides a convenient interface for reading data such as a file
// of newline-delimited lines of text. Successive calls to the Scan method
// will step through the 'tokens' of a file, skipping the bytes between the
// tokens. The specification of a token is defined by a split function of type
// SplitFunc; the default split function breaks the input into lines with line
// termination stripped.
//
// It is a generic wrapper around [bufio.Scanner]. Callers receive tokens as
// type S — either string or []byte — without a copy. The split function
// always operates on []byte internally; only the final delivery to the caller
// via Token is typed.
//
// When S is string, Token returns a string backed by the scanner's internal
// buffer. That string is only valid until the next call to Scan.
type Scanner[S text.String] struct {
	s *stdbufio.Scanner
}

// NewScanner returns a new Scanner to read from r.
// The split function defaults to ScanLines.
func NewScanner[S text.String](r io.Reader) *Scanner[S] {
	return &Scanner[S]{s: stdbufio.NewScanner(r)}
}

// Err returns the first non-EOF error encountered by the Scanner.
func (s *Scanner[S]) Err() error { return s.s.Err() }

// Token returns the most recent token generated by a call to Scan.
// The underlying array may point to data that will be overwritten by a
// subsequent call to Scan. It does no allocation.
func (s *Scanner[S]) Token() S { return asS[S](s.s.Bytes()) }

// Scan advances the Scanner to the next token, which will then be available
// through the Token method. It returns false when the scan stops, either by
// reaching the end of the input or an error. After Scan returns false, the
// Err method will return any error that occurred during scanning, except that
// if it was io.EOF, Err will return nil.
func (s *Scanner[S]) Scan() bool { return s.s.Scan() }

// Split sets the split function for the Scanner. The default split function
// is ScanLines. Split panics if it is called after scanning has started.
func (s *Scanner[S]) Split(split SplitFunc) { s.s.Split(split) }

// Buffer sets the initial buffer to use when scanning and the maximum size of
// buffer that may be allocated during scanning. Buffer panics if it is called
// after scanning has started.
func (s *Scanner[S]) Buffer(buf []byte, max int) { s.s.Buffer(buf, max) }

// Predefined split functions for use with a Scanner.
var (
	ScanBytes = stdbufio.ScanBytes
	ScanLines = stdbufio.ScanLines
	ScanRunes = stdbufio.ScanRunes
	ScanWords = stdbufio.ScanWords
)

// asS converts b to S using an unsafe string header when S is a string type,
// avoiding a copy. The result shares the lifetime of b.
func asS[S text.String](b []byte) S {
	if len(b) == 0 {
		var zero S
		return zero
	}
	var zero S
	if reflect.TypeOf(zero).Kind() == reflect.String {
		return S(unsafe.String(&b[0], len(b)))
	}
	return S(b)
}
